- sink: stderr
  level: TRACE
  format: |+
    <dim><green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | {file.path}:{line}</dim>
    <level>{message}</level>
- sink: logs/info.log
  level: INFO
  format: |+
    <dim><green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | {file.path}:{line}</dim>
    <level>{message}</level>
  mode: w
- sink: logs/debug.log
  level: DEBUG
  format: |+
    <dim><green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | {file.path}:{line}</dim>
    <level>{message}</level>
  mode: w
